services:
  nats:
    image: nats:2.10-alpine
    container_name: nats
    command: [ "-js", "-sd", "/data", "--http_port", "8222" ]
    ports:
      - "4222:4222" # NATS client
      - "8222:8222" # NATS monitoring UI
    volumes:
      - nats-data:/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.17
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --name=node1
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=node1=http://0.0.0.0:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    ports:
      - "2379:2379" # etcd client API
      - "2380:2380" # etcd peer communication
    volumes:
      - etcd-data:/etcd-data

volumes:
  nats-data:
  redis-data:
  etcd-data:
